spring:
  application:
    name: core-banking-service
  datasource:
    url: jdbc:postgresql://localhost:5431/core-banking
    username: postgres
    password: Postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db.changelog-master.yml

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: ${spring.application.name}