server:
  port: 8083

spring:
  application:
    name: utility-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5428/utility_payment
    username: postgres
    password: Postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info